import type { Catalog, Category, DeliveryZone, Product, WorkingHour } from "@/lib/types";

export const defaultWorkingHours: WorkingHour[] = [
  { weekday: 0, slot: 1, opensAt: "18:00", closesAt: "23:30", isClosed: false },
  { weekday: 1, slot: 1, opensAt: "18:00", closesAt: "23:30", isClosed: true },
  { weekday: 2, slot: 1, opensAt: "18:00", closesAt: "23:30", isClosed: false },
  { weekday: 3, slot: 1, opensAt: "18:00", closesAt: "23:30", isClosed: false },
  { weekday: 4, slot: 1, opensAt: "18:00", closesAt: "23:30", isClosed: false },
  { weekday: 5, slot: 1, opensAt: "18:00", closesAt: "23:30", isClosed: false },
  { weekday: 6, slot: 1, opensAt: "18:00", closesAt: "23:30", isClosed: false },
];

export const deliveryZones: DeliveryZone[] = [];

export const categories: Category[] = [
  { id: "tradicionais", name: "Tradicionais", description: "Os clássicos da Dog do Chef", sortOrder: 1 },
  { id: "prensadoes", name: "Prensadões", description: "Prensados de respeito", sortOrder: 2 },
  { id: "combos", name: "Combos", description: "Escolhas para matar a fome", sortOrder: 3 },
  { id: "dog-no-pote", name: "Dog no Pote (Gratinados)", description: "Quentinhos, cremosos e gratinados", sortOrder: 4 },
  { id: "porcoes", name: "Porções", description: "Para compartilhar", sortOrder: 5 },
  { id: "bebidas", name: "Bebidas", description: "Geladas e naturais", sortOrder: 6 },
];

type ProductDefinition = Omit<Product, "imageUrl" | "images" | "showcaseOrder" | "featured" | "inShowcase"> & {
  featured?: boolean;
};

const productDefinitions: ProductDefinition[] = [
  {
    id: "tradicional-hot-dog-tradicional",
    categoryId: "tradicionais",
    name: "Hot Dog Tradicional",
    description: "Pão, molhos, purê, salsicha Perdigão e batata palha.",
    priceCents: 1300,
    emoji: "🌭",
    isAvailable: true,
    prepMinutes: 15,
    optionGroups: [],
  },
  {
    id: "tradicional-hot-dog-duplo",
    categoryId: "tradicionais",
    name: "Hot Dog Duplo",
    description: "Pão, molhos, molho de alho, purê, 2 salsichas Perdigão, milho e batata palha.",
    priceCents: 1800,
    emoji: "🌭",
    isAvailable: true,
    prepMinutes: 18,
    optionGroups: [],
  },
  {
    id: "tradicional-hot-dog-bacon",
    categoryId: "tradicionais",
    name: "Hot Dog Bacon",
    description: "Pão, molhos, molho de alho, purê, salsichas Perdigão, bacon, milho e batata palha.",
    priceCents: 2100,
    emoji: "🥓",
    isAvailable: true,
    prepMinutes: 18,
    optionGroups: [],
  },
  {
    id: "tradicional-hot-dog-calabresa",
    categoryId: "tradicionais",
    name: "Hot Dog Calabresa",
    description: "Pão, molhos, molho de alho, purê, calabresa, salsichas Perdigão, milho e batata palha.",
    priceCents: 2100,
    emoji: "🌭",
    isAvailable: true,
    prepMinutes: 18,
    optionGroups: [],
  },
  {
    id: "prensado-hot-dog-tradicional",
    categoryId: "prensadoes",
    name: "Hot Dog Tradicional",
    description: "Pão, molhos, molho de alho, purê, vinagrete e batata palha.",
    priceCents: 1600,
    emoji: "🌭",
    isAvailable: true,
    prepMinutes: 15,
    optionGroups: [],
  },
  {
    id: "prensado-hot-dog-duplo",
    categoryId: "prensadoes",
    name: "Hot Dog Duplo",
    description: "Pão, molhos, molho de alho, purê, vinagrete, 2 salsichas Perdigão, batata palha e milho.",
    priceCents: 2000,
    emoji: "🌭",
    isAvailable: true,
    prepMinutes: 18,
    optionGroups: [],
  },
  {
    id: "prensado-hot-dog-catupiry",
    categoryId: "prensadoes",
    name: "Hot Dog Catupiry",
    description: "Pão, molhos, molho de alho, purê, vinagrete, salsicha Perdigão, catupiry Scala, milho e batata palha.",
    priceCents: 2200,
    emoji: "🧀",
    isAvailable: true,
    prepMinutes: 20,
    optionGroups: [],
  },
  {
    id: "prensado-hot-dog-cheddar",
    categoryId: "prensadoes",
    name: "Hot Dog Cheddar",
    description: "Pão, molhos, molho de alho, purê, vinagrete, salsicha Perdigão, cheddar Scala, milho e batata palha.",
    priceCents: 2200,
    emoji: "🧀",
    isAvailable: true,
    prepMinutes: 20,
    optionGroups: [],
  },
  {
    id: "prensado-hot-dog-calabresa",
    categoryId: "prensadoes",
    name: "Hot Dog Calabresa",
    description: "Pão, molhos, molho de alho, purê, vinagrete, salsicha Perdigão, calabresa, milho e batata palha.",
    priceCents: 2300,
    emoji: "🌭",
    isAvailable: true,
    prepMinutes: 20,
    optionGroups: [],
  },
  {
    id: "prensado-alcatra",
    categoryId: "prensadoes",
    name: "Prensadão Alcatra",
    description: "Pão, molhos, molho de alho, purê, vinagrete, mussarela, alcatra fatiada, salsicha Perdigão, milho e batata palha.",
    priceCents: 2500,
    emoji: "🥩",
    isAvailable: true,
    prepMinutes: 25,
    optionGroups: [],
  },
  {
    id: "prensado-dog-do-chef",
    categoryId: "prensadoes",
    name: "Dog do Chef",
    description: "Pão, molhos, molho de alho, purê, vinagrete, 2 salsichas Perdigão, bacon, catupiry Scala, mussarela, milho e batata palha.",
    priceCents: 3000,
    emoji: "👨‍🍳",
    isAvailable: true,
    prepMinutes: 25,
    optionGroups: [],
  },
  {
    id: "prensado-dog-monstro",
    categoryId: "prensadoes",
    name: "Dog Monstro",
    description: "Pão, molhos, molho de alho, purê, vinagrete, 2 salsichas Perdigão, alcatra, bacon, calabresa, catupiry ou cheddar Scala, mussarela, milho e batata palha.",
    priceCents: 3800,
    emoji: "👹",
    isAvailable: true,
    prepMinutes: 30,
    optionGroups: [],
  },
  {
    id: "prensado-picanha",
    categoryId: "prensadoes",
    name: "Prensadão Picanha",
    description: "Pão, molhos, molho de alho, purê, vinagrete, mussarela, picanha fatiada, milho e batata palha.",
    priceCents: 4000,
    emoji: "🥩",
    isAvailable: true,
    prepMinutes: 30,
    optionGroups: [],
  },
  {
    id: "combo-tradicional",
    categoryId: "combos",
    name: "Combo Tradicional",
    description: "1 Hot Dog Tradicional e 1 Refrigerante Lata.",
    priceCents: 1800,
    emoji: "🌭",
    isAvailable: true,
    prepMinutes: 18,
    optionGroups: [],
  },
  {
    id: "combo-simples",
    categoryId: "combos",
    name: "Combo Simples",
    description: "1 Hot Dog Simples Prensado e 1 Refrigerante Lata.",
    priceCents: 2300,
    emoji: "🌭",
    isAvailable: true,
    prepMinutes: 20,
    optionGroups: [],
  },
  {
    id: "combo-do-chef",
    categoryId: "combos",
    name: "Combo do Chef",
    description: "2 Dog do Chef e 2 Refrigerantes Lata.",
    priceCents: 6800,
    emoji: "👨‍🍳",
    isAvailable: true,
    featured: true,
    highlight: "Mais pedido",
    prepMinutes: 30,
    optionGroups: [],
  },
  {
    id: "combo-completo",
    categoryId: "combos",
    name: "Combo Completo",
    description: "2 Hot Dogs Duplos Prensados, porção de batata frita simples e 1 Refrigerante 600 ml.",
    priceCents: 7500,
    emoji: "🍟",
    isAvailable: true,
    featured: true,
    highlight: "Melhor escolha",
    prepMinutes: 30,
    optionGroups: [],
  },
  {
    id: "gratinado-simples",
    categoryId: "dog-no-pote",
    name: "Gratinado Simples",
    description: "Pão, salsicha Perdigão, purê, batata palha, ketchup, mostarda e mussarela gratinada.",
    priceCents: 1800,
    emoji: "🥘",
    isAvailable: true,
    prepMinutes: 20,
    optionGroups: [],
  },
  {
    id: "gratinado-especial",
    categoryId: "dog-no-pote",
    name: "Gratinado Especial",
    description: "Pão, 2 salsichas Perdigão, purê, milho, vinagrete, batata palha, molho de alho, ketchup, mostarda e mussarela gratinada.",
    priceCents: 2200,
    emoji: "🥘",
    isAvailable: true,
    prepMinutes: 22,
    optionGroups: [],
  },
  {
    id: "gratinado-bacon-especial",
    categoryId: "dog-no-pote",
    name: "Gratinado Bacon Especial",
    description: "Pão, 2 salsichas Perdigão, purê, milho, vinagrete, batata palha, bacon, catupiry, molho de alho, ketchup, mostarda e mussarela gratinada.",
    priceCents: 2800,
    emoji: "🥓",
    isAvailable: true,
    prepMinutes: 25,
    optionGroups: [],
  },
  {
    id: "gratinado-calabresa-especial",
    categoryId: "dog-no-pote",
    name: "Gratinado Calabresa Especial",
    description: "Pão, 2 salsichas Perdigão, purê, milho, vinagrete, batata palha, calabresa, catupiry, molho de alho, ketchup, mostarda e mussarela gratinada.",
    priceCents: 2800,
    emoji: "🥘",
    isAvailable: true,
    prepMinutes: 25,
    optionGroups: [],
  },
  {
    id: "porcao-batata-simples",
    categoryId: "porcoes",
    name: "Porção de Batata Simples",
    description: "",
    priceCents: 3500,
    emoji: "🍟",
    isAvailable: true,
    prepMinutes: 15,
    optionGroups: [],
  },
  {
    id: "porcao-batata-completa",
    categoryId: "porcoes",
    name: "Porção de Batata Completa",
    description: "Batata, catupiry ou cheddar Scala, bacon e mussarela.",
    priceCents: 4500,
    emoji: "🍟",
    isAvailable: true,
    prepMinutes: 20,
    optionGroups: [],
  },
  {
    id: "bebida-refrigerante-lata",
    categoryId: "bebidas",
    name: "Refrigerante Lata",
    description: "",
    priceCents: 600,
    emoji: "🥤",
    isAvailable: true,
    prepMinutes: 2,
    optionGroups: [],
  },
  {
    id: "bebida-coca-cola-1-litro",
    categoryId: "bebidas",
    name: "Coca-Cola 1 Litro",
    description: "",
    priceCents: 1100,
    emoji: "🥤",
    isAvailable: true,
    prepMinutes: 2,
    optionGroups: [],
  },
  {
    id: "bebida-suco-del-valle-lata",
    categoryId: "bebidas",
    name: "Suco Del Valle Lata",
    description: "",
    priceCents: 800,
    emoji: "🧃",
    isAvailable: true,
    prepMinutes: 2,
    optionGroups: [],
  },
  {
    id: "bebida-agua-sem-gas",
    categoryId: "bebidas",
    name: "Água sem Gás",
    description: "",
    priceCents: 350,
    emoji: "💧",
    isAvailable: true,
    prepMinutes: 2,
    optionGroups: [],
  },
  {
    id: "bebida-agua-com-gas",
    categoryId: "bebidas",
    name: "Água com Gás",
    description: "",
    priceCents: 350,
    emoji: "💧",
    isAvailable: true,
    prepMinutes: 2,
    optionGroups: [],
  },
  {
    id: "bebida-refrigerante-600-ml",
    categoryId: "bebidas",
    name: "Refrigerante 600 ml",
    description: "",
    priceCents: 900,
    emoji: "🥤",
    isAvailable: true,
    prepMinutes: 2,
    optionGroups: [],
  },
  {
    id: "bebida-cerveja-600-ml",
    categoryId: "bebidas",
    name: "Cerveja 600 ml",
    description: "",
    priceCents: 1200,
    emoji: "🍺",
    isAvailable: true,
    prepMinutes: 2,
    optionGroups: [],
  },
  {
    id: "bebida-suco-laranja-jarra-500-ml",
    categoryId: "bebidas",
    name: "Suco Laranja Natural · Jarra 500 ml",
    description: "",
    priceCents: 1500,
    emoji: "🍊",
    isAvailable: true,
    prepMinutes: 5,
    optionGroups: [],
  },
  {
    id: "bebida-suco-laranja-copo-300-ml",
    categoryId: "bebidas",
    name: "Suco Laranja Natural · Copo 300 ml",
    description: "",
    priceCents: 800,
    emoji: "🍊",
    isAvailable: true,
    prepMinutes: 5,
    optionGroups: [],
  },
];

function imageForProduct(product: ProductDefinition) {
  if (product.categoryId === "dog-no-pote") return "/images/dogchef/dog-no-pote.webp";
  if (product.categoryId === "porcoes") return "/images/dogchef/batata-completa.webp";
  if (product.categoryId === "bebidas") return "/images/dogchef/bebidas.webp";
  if (product.categoryId === "combos") return "/images/dogchef/hero-dog-do-chef.webp";
  if (["prensado-alcatra", "prensado-dog-monstro", "prensado-picanha"].includes(product.id)) {
    return "/images/dogchef/dog-monstro.webp";
  }
  if (product.id.includes("bacon") || product.id.includes("calabresa")) {
    return "/images/dogchef/dog-monstro.webp";
  }
  if (product.categoryId === "prensadoes") return "/images/dogchef/hot-dog-cremoso.webp";
  return "/images/dogchef/hot-dog-tradicional.webp";
}

export const products: Product[] = productDefinitions.map((product) => ({
  ...product,
  imageUrl: imageForProduct(product),
  images: [{ id: `seed-${product.id}`, url: imageForProduct(product), isMain: true, sortOrder: 0 }],
  featured: Boolean(product.featured),
  inShowcase: Boolean(product.featured),
  showcaseOrder: product.featured ? productDefinitions.filter((candidate) => candidate.featured).findIndex((candidate) => candidate.id === product.id) : 0,
}));

export function seededCatalog(): Catalog {
  return {
    categories,
    products,
    deliveryZones,
    defaultDeliveryFeeCents: 800,
    acceptingOrders: true,
    pixConfigured: Boolean(process.env.MERCADO_PAGO_ACCESS_TOKEN),
    whatsappConfigured: Boolean(process.env.NEXT_PUBLIC_WHATSAPP_NUMBER),
    whatsappUrl: process.env.NEXT_PUBLIC_WHATSAPP_NUMBER
      ? `https://wa.me/${process.env.NEXT_PUBLIC_WHATSAPP_NUMBER.replace(/\D/g, "")}`
      : undefined,
    hoursLabel: "Ter–Dom · 18h às 23h30",
    workingHours: defaultWorkingHours,
  };
}
